---
title: "BinanceScraper"
output: html_document
---

```{r libraries}
    
  library(httr)
  library(rlist)

```



```{r Scrape}

res <- GET(url = "https://api.binance.com",
           path = "/api/v1/klines",
           query = list (
              symbol = "IOTABTC",
              interval = "1d"
            )
          )
content(res, as="parsed")

res <- GET(url = "https://api.binance.com",
           path = "/api/v1/exchangeInfo",
           query = list (
             
            )
          )

content(res, as="parsed")


res <- GET(url = "https://api.binance.com",
           path = "/api/v1/time",
           query = list (
             
            )
          )
content(res, as="parsed")


```



```{r Get symbols}

    res <- GET(url = "https://api.binance.com",
               path = "/api/v1/exchangeInfo",
               query = list (
                  )
              )
        
    df <- content(res, as = "parsed")
    df1 <- df
    symbols <- df1$symbols %>%
               unlist() %>%
               matrix(nrow = length(df1$symbols), byrow = TRUE) %>%
               data.frame(stringsAsFactors = FALSE) %>%
               select(X1, X3, X5)
    
    names(symbols) <- c("symbol", "baseAsset", "quoteAsset")
    
    symbols %>% filter(quoteAsset == "BTC") %>% View()
    last_date <- max(df_marketdata$date, na.rm = TRUE)
    last_rank <- df_marketdata %>% filter(date == last_date)
    listed_coins <- left_join(symbols %>% filter(quoteAsset == "BTC"), last_rank, by = c("baseAsset" = "symbol"))
    
    
    
              data.frame(matrix(unlist(df$symbols), nrow=length(df$symbols), byrow = TRUE),stringsAsFactors = FALSE)
    symbols 


```

````{r Scraper python to R}

    date_to_milliseconds <- function(datetime){
      milliseconds = as.numeric(as.POSIXct(datetime))
      return(milliseconds)
    }
    
    
    
    milliseconds_to_date <- function(milliseconds){
      date <- as.POSIXct((milliseconds), origin = "1970-01-01")
      return(date)
    }
    
    milliseconds_to_date(date_to_milliseconds("2016-01-01 12:00:00"))
    
    
    get_historical_klines <- function(symbol, 
                                      interval  = 86400, 
                                      start_str = "2016-01-01 12:00:00", 
                                      end_str   = "2018-01-03 12:00:00")

    # Get Historical Klines from Binance
    # See dateparse docs for valid start and end string formats http://dateparser.readthedocs.io/en/latest/
    # If using offset strings for dates add "UTC" to date string e.g. "now UTC", "11 hours ago UTC"
    # :param symbol: Name of symbol pair e.g BNBBTC
    # :type symbol: str
    # :param interval: Biannce Kline interval
    # :type interval: str
    # :param start_str: Start date string in UTC format
    # :type start_str: str
    # :param end_str: optional - end date string in UTC format
    # :type end_str: str
    # :return: list of OHLCV values
    
    # create the Binance client, no need for api key
   # client = Client("", "")

    # init our list
    output_data <- list()

    # setup the max limit
    limit = 500

    # interval in seconds, used for shifting requests in time
    timeframe = interval

    # convert our date strings to milliseconds
    start_ts = as.numeric(as.POSIXct(start_str))

    # if an end time was passed convert it
    if (is.na(end_str) == FALSE) {end_ts = as.numeric(as.POSIXct(end_str))}

    idx <- 0
    # it can be difficult to know when a symbol was listed on Binance so allow start time to be before list date
    symbol_existed = FALSE
    while TRUE {
        # fetch the klines from start_ts up to max 500 entries or the end_ts if set
      
        res <- GET(url = "https://api.binance.com",
                   path = "/api/v1/klines",
                   query = list (
                       symbol = "ETHBTC"
                       , interval = "1d"
                       , limit = limit
                       , startTime = start_ts
                       #, endTime = end_ts
                      )
                  )
        
        df <- content(res, as = "parsed")
        df <- data.frame(matrix(unlist(df), nrow=length(df), byrow = TRUE),stringsAsFactors = FALSE)
        df$X1 <- milliseconds_to_date(as.numeric(df$X1)/1000)
        
        names(df) <- c("Open.time", "Open", "High", "Low", "Close", "Volume", "Close.time", "Quote asset volume", "Number of trades", "Taker buy base asset volume", "Taker buy quote asset volume", "Ignore")
        
        # handle the case where our start date is before the symbol pair listed on Binance
        if (symbol_existed == FALSE & is.null(length(temp_data))  0) {
            symbol_existed = TRUE
        }

        if symbol_existed:
            # append this loops data to our output data
            output_data <- add.rows(temp_data)
            list.append(output_data, temp_data)

            # update our start timestamp using the last value in the array and add the interval timeframe
            start_ts <- temp_data[len(temp_data) - 1][0] + timeframe
        else:
            # it wasn't listed yet, increment our start date
            start_ts <- start_ts + timeframe

        idx += 1
        # check if we received less than the required limit and exit the loop
        if length(temp_data) < limit {
            # exit the while loop
            break
        }
        # sleep after every 3rd call to be kind to the API
        if idx % 3 == 0:
            sys.sleep(1)

    return output_data
```
